name: Current Master Checks
on: [push]
jobs:
  Test-And-Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - run: echo "executed on ${{ runner.os }}"
      - run: echo "running for ${{ github.repository }} -- ${{ github.ref }}."

      - name: checkout repository
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: run tests
        run: |
          coverage run -m pytest
          coverage report

      - name: build package
        run: python -m build
