name: Master Checks
on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }}"
      - run: echo "executed on ${{ runner.os }}"
      - run: echo "running for ${{ github.repository }} -- ${{ github.ref }}."

      - name: checkout repository
      - uses: actions/checkout@v3

      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: "poetry"

      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - run: poetry run pytest
      - uses: jakebailey/pyright-action@v2

      - name: run tests
        run: |
          coverage run -m pytest
          coverage report

      - name: build package
        run: python -m build
