name: Master Checks
on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job triggered by ${{ github.event_name }}"
          echo "executed on ${{ runner.os }}"
          echo "running for ${{ github.repository }} -- ${{ github.ref }}."

      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "poetry"

      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - run: poetry run pyright src
      - run: poetry run coverage run -m pytest
      - run: poetry run coverage report

      - run: poetry build
